### ISSUE TITLE
Thumbprint needed

### ISSUE THREAD

**Issue by andersem** [witnessmenow/arduino-instagram-stats#6]
I followed this example to do this on my ESP8266, but I never got a response from IG. It turned out I needed to put the thumbprint of Instagram's website on the secureClient.

```
const char fingerprint[] PROGMEM = "a383820e882bf0c3de4de058b5fda7cdba772779";
```

and 

```
client.setFingerprint(fingerprint);
```

**Comment by andersem** [comment]
The problem with this is that the certificate changes every once in a while, so it's not a lasting solution.

**Comment by witnessmenow** [comment]
I've added to the example how to skip needing a fingerprint for latest
esp8266 using client.useInsecure() (or something like that)

Since this is a public read only endpoint it's hitting I don't think it's
important to check the fingerprint

On 20 Jan 2019 14:03, "Anders Emil Salvesen" <notifications@github.com>
wrote:

The problem with this is that the certificate changes every once in a
while, so it's not a lasting solution.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/witnessmenow/arduino-instagram-stats/issues/6#issuecomment-455869079>,
or mute the thread

**Comment by andersem** [comment]
Oh, thanks! I missed that.

**Comment by witnessmenow** [comment]
Great! I only added it in the last week so it would be easy to miss!
